# Built with Jekyll 3.2.0

# Setup
title:               Sketchbook.
tagline:             'Scribbles and sketches.'
description:         'Sketchbook'
url:                 'http://yngtodd.github.io'
baseurl:             '/sketchbook'

# About/contact
author:
  name:              M. Todd Young 
  url:               
  email:             youngmt1@ornl.gov

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."